apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: s5ndeye-monitoring
data:
  alertmanager.yaml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 's5ndeye.wft@gmail.com'
      smtp_auth_username: 's5ndeye.wft@gmail.com'
      smtp_auth_password: '${SMTP_PASSWORD}'

    route:
      receiver: default
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 3h
      routes:
        - match:
            severity: critical
          receiver: slack
        - match:
            severity: warning
          receiver: email

    receivers:
      - name: default
        slack_configs:
          - send_resolved: true
            webhook_url: 'https://hooks.slack.com/services/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'
            channel: '#all-wft-intern'

      - name: slack
        slack_configs:
          - send_resolved: true
            webhook_url: 'https://hooks.slack.com/services/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'
            channel: '#all-wft-intern'

      - name: email
        email_configs:
          - to: 's5ndeye.wft@gmail.com'
            send_resolved: true
