apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-alert-rules
  namespace: s5ndeye-monitoring
spec:
  groups:
    - name: example.rules
      rules:
        - alert: HighCPUUsage
          expr: rate(process_cpu_seconds_total[1m]) > 0.01
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: High CPU usage detected
            description: 'CPU usage has been above 1% over the last minute'
