apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: s5ndeye-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets: ["alertmanager:9093"]

    rule_files:
      - /etc/prometheus/rules/prometheus-alerts-rules.yml

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
