apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: s5ndeye-monitoring  
spec:
  type: NodePort
  selector:
    app: prometheus            
  ports:
    - protocol: TCP
      port: 9090                
      targetPort: 9090          
      nodePort: 31000  